# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1631, 1039)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videolabel = QtWidgets.QLabel(self.centralwidget)
        self.videolabel.setGeometry(QtCore.QRect(13, 13, 1600, 800))
        self.videolabel.setAutoFillBackground(False)
        self.videolabel.setStyleSheet("background-color: lightgray;\n"
"text-align:center")
        self.videolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videolabel.setObjectName("videolabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 820, 503, 101))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.fastfwdButton = QtWidgets.QPushButton(self.groupBox)
        self.fastfwdButton.setObjectName("fastfwdButton")
        self.gridLayout.addWidget(self.fastfwdButton, 1, 3, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 1, 0, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout.addWidget(self.pauseButton, 1, 1, 1, 1)
        self.rewindButton = QtWidgets.QPushButton(self.groupBox)
        self.rewindButton.setObjectName("rewindButton")
        self.gridLayout.addWidget(self.rewindButton, 1, 2, 1, 1)
        self.videoSlider = QtWidgets.QSlider(self.groupBox)
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setObjectName("videoSlider")
        self.gridLayout.addWidget(self.videoSlider, 0, 0, 1, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(790, 820, 141, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(20, 30, 111, 53))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.est_x = QtWidgets.QLabel(self.widget)
        self.est_x.setObjectName("est_x")
        self.horizontalLayout_2.addWidget(self.est_x)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.est_y = QtWidgets.QLabel(self.widget)
        self.est_y.setObjectName("est_y")
        self.horizontalLayout.addWidget(self.est_y)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 820, 261, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.curr_frame = QtWidgets.QLabel(self.groupBox_3)
        self.curr_frame.setObjectName("curr_frame")
        self.horizontalLayout_3.addWidget(self.curr_frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(970, 820, 261, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.jumpToNextCrackButton = QtWidgets.QPushButton(self.groupBox_4)
        self.jumpToNextCrackButton.setObjectName("jumpToNextCrackButton")
        self.gridLayout_3.addWidget(self.jumpToNextCrackButton, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1250, 820, 141, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbPatches = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbPatches.setChecked(True)
        self.cbPatches.setObjectName("cbPatches")
        self.gridLayout_4.addWidget(self.cbPatches, 1, 0, 1, 1)
        self.cbNaiveBayes = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbNaiveBayes.setChecked(True)
        self.cbNaiveBayes.setObjectName("cbNaiveBayes")
        self.gridLayout_4.addWidget(self.cbNaiveBayes, 2, 0, 1, 1)
        self.cbMotionEstimator = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbMotionEstimator.setChecked(True)
        self.cbMotionEstimator.setObjectName("cbMotionEstimator")
        self.gridLayout_4.addWidget(self.cbMotionEstimator, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(1400, 830, 141, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.spinNBThreeshold = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinNBThreeshold.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.spinNBThreeshold.setMaximum(1000)
        self.spinNBThreeshold.setObjectName("spinNBThreeshold")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 131, 19))
        self.label_4.setObjectName("label_4")
        self.groupBox_6.raise_()
        self.videolabel.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1631, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_video_footage = QtWidgets.QAction(MainWindow)
        self.actionLoad_video_footage.setObjectName("actionLoad_video_footage")
        self.actionSelect_SPR_file = QtWidgets.QAction(MainWindow)
        self.actionSelect_SPR_file.setObjectName("actionSelect_SPR_file")
        self.actionExit_Application = QtWidgets.QAction(MainWindow)
        self.actionExit_Application.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit_Application.setObjectName("actionExit_Application")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSelect_Output_Video = QtWidgets.QAction(MainWindow)
        self.actionSelect_Output_Video.setObjectName("actionSelect_Output_Video")
        self.actionEnable_capture_to_file = QtWidgets.QAction(MainWindow)
        self.actionEnable_capture_to_file.setCheckable(True)
        self.actionEnable_capture_to_file.setChecked(True)
        self.actionEnable_capture_to_file.setObjectName("actionEnable_capture_to_file")
        self.menuFile.addAction(self.actionLoad_video_footage)
        self.menuFile.addAction(self.actionSelect_SPR_file)
        self.menuFile.addAction(self.actionExit_Application)
        self.menuCapture.addAction(self.actionSelect_Output_Video)
        self.menuCapture.addAction(self.actionEnable_capture_to_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videolabel.setText(_translate("MainWindow", "NO VIDEO LOADED"))
        self.groupBox.setTitle(_translate("MainWindow", "Video Playback"))
        self.fastfwdButton.setText(_translate("MainWindow", ">>"))
        self.playButton.setText(_translate("MainWindow", ">"))
        self.pauseButton.setText(_translate("MainWindow", " ||"))
        self.rewindButton.setText(_translate("MainWindow", "<<"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Motion Estimator"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.est_x.setText(_translate("MainWindow", "0.00"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.est_y.setText(_translate("MainWindow", "0.00"))
        self.groupBox_3.setTitle(_translate("MainWindow", "VideoReader"))
        self.label_3.setText(_translate("MainWindow", "Frame:"))
        self.curr_frame.setText(_translate("MainWindow", "0/0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Crack Inspector"))
        self.jumpToNextCrackButton.setText(_translate("MainWindow", "Jump to next crack"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Display"))
        self.cbPatches.setText(_translate("MainWindow", "Patches"))
        self.cbNaiveBayes.setText(_translate("MainWindow", "Naive Bayes"))
        self.cbMotionEstimator.setText(_translate("MainWindow", "M.E."))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_4.setText(_translate("MainWindow", "N.B. Threeshold"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.actionLoad_video_footage.setText(_translate("MainWindow", "Select video footage"))
        self.actionSelect_SPR_file.setText(_translate("MainWindow", "Select SPR file"))
        self.actionExit_Application.setText(_translate("MainWindow", "Exit Application"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionSelect_Output_Video.setText(_translate("MainWindow", "Select Output Video"))
        self.actionEnable_capture_to_file.setText(_translate("MainWindow", "Enable capture to file"))

